apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ai-app-deployment
  labels:
	app: my-ai-app
spec:
  replicas: 1
  selector:
	matchLabels:
	  app: my-ai-app
  template:
	metadata:
	  labels:
		app: my-ai-app
	spec:
	  containers:
	  - name: my-ai-app-container
		image: my-ai-app:1.0.0 # Our locally built image
		imagePullPolicy: Never   # Crucial for local images!
		ports:
		- containerPort: 80      # Nginx listens on port 80